import Head from 'next/head'
import { Footer, Header, Menu } from '../components'

export default function Home() {
  return (
    <div className='flex flex-col h-full bg-[url("/photography-bg.jpg")] bg-center bg-cover'>
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Photography Portfolio generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='grow'>
      <Menu />
      </main>
      <Footer />
    </div>
  )
}
