import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Photography Portfolio generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1>Hello</h1>
      </main>
      <footer></footer>
    </div>
  )
}
