import Head from 'next/head'
import Image from 'next/image'
import { Footer, Header, Menu } from '../components'
import bgImage from '../public/photography-bg.jpg'

export default function Home() {
  return (
    <div className='h-fulloverflow-auto'>
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Photography Portfolio generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image className='fixed left-0 top-0 z-0' src={bgImage} alt='bg-image' placeholder='blur' />
      <div className="fixed left-0 top-0 w-full h-full z-10 from-stone-900 bg-gradient-to-t" />
      <Header />
      <main className='pt-[110px] z-20 relative'>
      <Menu />
      </main>
      <Footer />
    </div>
  )
}
